include:
  - project: "platform/pipelines-templates"
    file: "/build/node/template-react-yarn.yml"
    ref: master

.docker-job:
  variables:
    COMMIT_SHA_FILEPATH: /usr/static/commit.sha

default:
  image: node:18


build-site:
  artifacts:
    paths:
      - .next
      - public
